import type { PortfolioGraph, PublicClaim, SystemDefinition } from "./types"

const claims: PublicClaim[] = [
  {
    evidenceKey: "form.contract-governance",
    systemId: "form-management",
    scope: "Typed DOCX contracts govern form output and validation boundaries.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports the described implementation; it does not establish a fresh runtime.",
  },
  {
    evidenceKey: "form.identity-authorization",
    systemId: "form-management",
    scope: "External identity and database authorization are separate gates before workspace access.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports the boundary; it does not establish a fresh authenticated runtime.",
  },
  {
    evidenceKey: "form.preview-persistence-audit",
    systemId: "form-management",
    scope: "Temporary Preview, Persisted Document, and Audit and Verification are distinct lifecycle outcomes.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports the lifecycle; it does not establish a fresh runtime.",
  },
  {
    evidenceKey: "form.corpus-gate",
    systemId: "form-management",
    scope: "A fresh local observation reported 213 of 213 locked and reviewed records.",
    classification: "VERIFIED_LOCAL",
    publicSafe: true,
    limitation: "The gate process exited nonzero because its summary was stale; the gate must not be described or styled as green.",
  },
  {
    evidenceKey: "vision.ingestion-dataset",
    systemId: "visionflow-studio",
    scope: "SHA-256 ingestion and dedupe lead to locked dataset versions and controlled annotation or pipeline inputs.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports the described implementation; it does not establish fresh service or storage runtime operation.",
  },
  {
    evidenceKey: "vision.queue-handoff",
    systemId: "visionflow-studio",
    scope: "A Queue Handoff separates request-side preparation from CV Worker execution.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports the cross-runtime route; it does not establish fresh Redis or worker runtime operation.",
  },
  {
    evidenceKey: "vision.inference-evaluation",
    systemId: "visionflow-studio",
    scope: "Guarded ONNX inference and deterministic evaluation hashes bind prediction and evaluation work.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports the guards and hashes; it does not establish fresh model or end-to-end runtime operation.",
  },
  {
    evidenceKey: "booking.revision-history",
    systemId: "production-booking-operations",
    scope: "Git history contains at least four reviewable pricing-model revisions represented by the Fourth Pricing Change.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Git and implemented-source evidence support the adaptation story; this is not live-production proof and publishes no real price.",
  },
  {
    evidenceKey: "booking.hold-snapshot-release",
    systemId: "production-booking-operations",
    scope: "Search, HOLD, immutable booking or pricing snapshot, and release-attestation boundaries exist in implemented source.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports these boundaries; it does not expose or establish live client, payment, room, or production state.",
  },
  {
    evidenceKey: "parkly.manual-review",
    systemId: "parkly",
    scope: "Low-confidence capture can hand control to Session or Manual Review before Audit.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports the operational handoff; it does not establish a fresh runtime.",
  },
  {
    evidenceKey: "parkly.ownership-lock",
    systemId: "parkly",
    scope: "Parkly implements a custom Redis ownership lock using ownership checks around NX/PX and Lua behavior.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "This is a custom ownership lock, never Redlock; current source inspection does not establish a fresh Redis runtime.",
  },
  {
    evidenceKey: "parkly.outbox-rail",
    systemId: "parkly",
    scope: "The outbox is an implemented delivery rail shown separately from Manual Review.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Do not draw or claim a direct Manual Review-to-outbox event link unless new evidence verifies it.",
  },
  {
    evidenceKey: "parkly.operational-rails",
    systemId: "parkly",
    scope: "Operational state, audit, device-health, SSE, and HMAC-related boundaries are present in source.",
    classification: "VERIFIED_IMPLEMENTED",
    publicSafe: true,
    limitation: "Current source inspection supports these components; it does not establish a fresh integrated runtime.",
  },
  {
    evidenceKey: "tft.component-assembly",
    systemId: "tft-local-copilot",
    scope: "FastAPI, local-model, vector-store, retrieval, streaming, and container components are represented in experimental source.",
    classification: "DOCUMENTED_ONLY",
    publicSafe: true,
    limitation: "Route-registration and migration gaps prevent a working end-to-end RAG claim.",
  },
]

const systems: SystemDefinition[] = [
  {
    id: "form-management",
    title: "Form Management",
    tier: "flagship",
    order: 1,
    anchor: "#system-form-management",
    publicAnchor: "DOCX Contract",
    summary: "The DOCX contract decides what every form is allowed to become.",
    evidenceBoundary: "Implemented source plus one qualified fresh local gate observation; no fresh runtime claim.",
    evidenceKeys: [
      "form.contract-governance",
      "form.identity-authorization",
      "form.preview-persistence-audit",
      "form.corpus-gate",
    ],
    topology: {
      layers: [
        { id: "form-authority", label: "Authority", meaning: "Identity and access ownership" },
        { id: "form-governance", label: "Governance and persistence", meaning: "Contract and document outcomes" },
        { id: "form-review", label: "Review", meaning: "Persisted audit boundary" },
      ],
      nodes: [
        { id: "form-identity", label: "Identity", responsibility: "Establish the external identity boundary.", layerId: "form-authority", sceneSlot: "left-far" },
        { id: "form-authorization", label: "Authorization", responsibility: "Decide access before workspace resolution.", layerId: "form-authority", sceneSlot: "center-far" },
        { id: "form-workspace", label: "Workspace", responsibility: "Own the resolved workspace state.", layerId: "form-governance", sceneSlot: "right-far" },
        { id: "form-docx-contract", label: "DOCX Contract", responsibility: "Govern allowed form fields and output.", layerId: "form-governance", sceneSlot: "left-mid" },
        { id: "form-temporary-preview", label: "Temporary Preview", responsibility: "Produce a non-persisted preview outcome.", layerId: "form-governance", sceneSlot: "center-near" },
        { id: "form-persisted-document", label: "Persisted Document", responsibility: "Produce the persisted governed outcome.", layerId: "form-governance", sceneSlot: "right-mid" },
        { id: "form-audit-verification", label: "Audit and Verification", responsibility: "Record and verify persisted work.", layerId: "form-review", sceneSlot: "right-near" },
      ],
      routes: [
        { id: "form-identity-to-authorization", from: "form-identity", to: "form-authorization", verb: "identifies for", kind: "dependency", evidenceKey: "form.identity-authorization" },
        { id: "form-authorization-to-workspace", from: "form-authorization", to: "form-workspace", verb: "permits", kind: "handoff", evidenceKey: "form.identity-authorization" },
        { id: "form-workspace-to-contract", from: "form-workspace", to: "form-docx-contract", verb: "resolves", kind: "dependency", evidenceKey: "form.contract-governance" },
        { id: "form-contract-to-preview", from: "form-docx-contract", to: "form-temporary-preview", verb: "governs", kind: "transition", evidenceKey: "form.preview-persistence-audit" },
        { id: "form-contract-to-persisted", from: "form-docx-contract", to: "form-persisted-document", verb: "governs", kind: "handoff", evidenceKey: "form.contract-governance" },
        { id: "form-persisted-to-audit", from: "form-persisted-document", to: "form-audit-verification", verb: "records to", kind: "transition", evidenceKey: "form.preview-persistence-audit" },
      ],
      activeHandoff: { routeId: "form-contract-to-persisted", focusNodeId: "form-persisted-document" },
    },
    narrative: {
      form: "contract",
      title: "The contract decides what the interface can become.",
      lead: "Identity proves who arrived. Authorization decides what that identity may resolve. The DOCX contract governs the output after both gates agree.",
      details: [
        "Temporary Preview is deliberately non-persisted and never inherits an Audit route.",
        "Persisted Document continues to Audit and Verification as a separate lifecycle outcome.",
        "A stale summary kept the corpus gate red even after 213 of 213 locked records were reviewed. Good.",
      ],
      claimInstanceIds: ["form-narrative-contract", "form-narrative-boundaries", "form-narrative-gate"],
    },
  },
  {
    id: "visionflow-studio",
    title: "VisionFlow Studio",
    tier: "flagship",
    order: 2,
    anchor: "#system-visionflow-studio",
    publicAnchor: "Queue Handoff",
    summary: "The request ends here. The job keeps moving.",
    evidenceBoundary: "Implemented source; no fresh service, storage, queue, model, or end-to-end runtime claim.",
    evidenceKeys: ["vision.ingestion-dataset", "vision.queue-handoff", "vision.inference-evaluation"],
    topology: {
      layers: [
        { id: "vision-request", label: "Request and data preparation", meaning: "Deterministic input ownership" },
        { id: "vision-runtime", label: "Runtime boundary", meaning: "Asynchronous execution ownership" },
        { id: "vision-result", label: "Result", meaning: "Prediction and evaluation identity" },
      ],
      nodes: [
        { id: "vision-media", label: "Media", responsibility: "Supply the ingested media identity.", layerId: "vision-request", sceneSlot: "left-far" },
        { id: "vision-dataset-version", label: "Dataset Version", responsibility: "Freeze the dataset input boundary.", layerId: "vision-request", sceneSlot: "center-far" },
        { id: "vision-annotation", label: "Annotation", responsibility: "Attach controlled training or evaluation labels.", layerId: "vision-request", sceneSlot: "left-mid" },
        { id: "vision-pipeline", label: "Pipeline", responsibility: "Assemble the submitted processing definition.", layerId: "vision-request", sceneSlot: "center-mid" },
        { id: "vision-queue-handoff", label: "Queue Handoff", responsibility: "End request-side ownership and enqueue work.", layerId: "vision-runtime", sceneSlot: "right-mid" },
        { id: "vision-cv-worker", label: "CV Worker", responsibility: "Own asynchronous computer-vision execution.", layerId: "vision-runtime", sceneSlot: "left-near" },
        { id: "vision-prediction", label: "Prediction", responsibility: "Persist or expose the produced prediction.", layerId: "vision-result", sceneSlot: "center-near" },
        { id: "vision-evaluation", label: "Evaluation", responsibility: "Compare outputs under deterministic evaluation identity.", layerId: "vision-result", sceneSlot: "right-near" },
      ],
      routes: [
        { id: "vision-media-to-dataset", from: "vision-media", to: "vision-dataset-version", verb: "versions into", kind: "transition", evidenceKey: "vision.ingestion-dataset" },
        { id: "vision-dataset-to-annotation", from: "vision-dataset-version", to: "vision-annotation", verb: "supplies", kind: "dependency", evidenceKey: "vision.ingestion-dataset" },
        { id: "vision-annotation-to-pipeline", from: "vision-annotation", to: "vision-pipeline", verb: "configures", kind: "dependency", evidenceKey: "vision.ingestion-dataset" },
        { id: "vision-pipeline-to-queue", from: "vision-pipeline", to: "vision-queue-handoff", verb: "submits", kind: "handoff", evidenceKey: "vision.queue-handoff" },
        { id: "vision-queue-to-worker", from: "vision-queue-handoff", to: "vision-cv-worker", verb: "dispatches to", kind: "handoff", evidenceKey: "vision.queue-handoff" },
        { id: "vision-worker-to-prediction", from: "vision-cv-worker", to: "vision-prediction", verb: "produces", kind: "transition", evidenceKey: "vision.inference-evaluation" },
        { id: "vision-prediction-to-evaluation", from: "vision-prediction", to: "vision-evaluation", verb: "is checked by", kind: "transition", evidenceKey: "vision.inference-evaluation" },
      ],
      activeHandoff: { routeId: "vision-queue-to-worker", focusNodeId: "vision-cv-worker" },
    },
    narrative: {
      form: "cross-runtime",
      title: "The request ends here. The job keeps moving.",
      lead: "Deterministic ingestion and locked dataset versions keep input identity stable before the Queue Handoff changes runtime ownership.",
      details: [
        "Controlled annotation and pipeline definitions prepare the job without keeping the HTTP request open.",
        "The CV Worker owns guarded inference after the handoff.",
        "Deterministic evaluation hashes bind the result, while source inspection stops short of fresh runtime proof.",
      ],
      claimInstanceIds: ["vision-narrative-ingestion", "vision-narrative-queue", "vision-narrative-evaluation"],
    },
  },
  {
    id: "production-booking-operations",
    title: "Production Booking & Operations Platform",
    tier: "flagship",
    order: 3,
    anchor: "#system-production-booking-operations",
    publicAnchor: "Fourth Pricing Change",
    summary: "Pricing changed again. The release loop already knew the route.",
    evidenceBoundary: "Git history and implemented source; generic title, no confidential values, and no live-production claim.",
    evidenceKeys: ["booking.revision-history", "booking.hold-snapshot-release"],
    topology: {
      layers: [
        { id: "booking-requirement", label: "Requirement", meaning: "Observed policy ownership" },
        { id: "booking-change", label: "Change", meaning: "Scoped implementation and verification" },
        { id: "booking-delivery", label: "Delivery", meaning: "Release and next-revision ownership" },
      ],
      nodes: [
        { id: "booking-feedback", label: "Feedback", responsibility: "Capture the observed requirement change.", layerId: "booking-requirement", sceneSlot: "left-mid" },
        { id: "booking-pricing-rule", label: "Pricing Rule", responsibility: "Express the revised pricing policy boundary.", layerId: "booking-requirement", sceneSlot: "center-far" },
        { id: "booking-implementation", label: "Implementation", responsibility: "Apply the scoped rule change.", layerId: "booking-change", sceneSlot: "right-far" },
        { id: "booking-verification", label: "Verification", responsibility: "Accept or reject the scoped change.", layerId: "booking-change", sceneSlot: "right-near" },
        { id: "booking-release", label: "Release", responsibility: "Move accepted work through the governed release path.", layerId: "booking-delivery", sceneSlot: "center-near" },
        { id: "booking-next-revision", label: "Next Revision", responsibility: "Return released learning to the next review.", layerId: "booking-delivery", sceneSlot: "left-near" },
      ],
      routes: [
        { id: "booking-feedback-to-rule", from: "booking-feedback", to: "booking-pricing-rule", verb: "revises", kind: "transition", evidenceKey: "booking.revision-history" },
        { id: "booking-rule-to-implementation", from: "booking-pricing-rule", to: "booking-implementation", verb: "governs", kind: "dependency", evidenceKey: "booking.revision-history" },
        { id: "booking-implementation-to-verification", from: "booking-implementation", to: "booking-verification", verb: "enters", kind: "handoff", evidenceKey: "booking.revision-history" },
        { id: "booking-verification-to-release", from: "booking-verification", to: "booking-release", verb: "accepts or rejects", kind: "transition", evidenceKey: "booking.revision-history" },
        { id: "booking-release-to-next", from: "booking-release", to: "booking-next-revision", verb: "informs", kind: "transition", evidenceKey: "booking.revision-history" },
        { id: "booking-next-to-feedback", from: "booking-next-revision", to: "booking-feedback", verb: "returns to", kind: "loop", evidenceKey: "booking.revision-history" },
      ],
      activeHandoff: { routeId: "booking-implementation-to-verification", focusNodeId: "booking-verification", label: "Fourth Pricing Change" },
    },
    narrative: {
      form: "adaptation-loop",
      title: "Pricing changed again. The release loop already knew the route.",
      lead: "The Fourth Pricing Change stands for a reviewable requirement revision without publishing the value or the identity behind it.",
      details: [
        "Feedback becomes a policy boundary before it becomes code.",
        "Implementation enters verification rather than jumping directly to release.",
        "The governed release returns learning to the next revision while immutable HOLD and snapshot boundaries keep decisions inspectable.",
      ],
      claimInstanceIds: ["booking-narrative-revision", "booking-narrative-snapshot"],
    },
  },
  {
    id: "parkly",
    title: "Parkly",
    tier: "supporting",
    order: 4,
    anchor: "#system-parkly",
    publicAnchor: "Manual Review Handoff",
    summary: "Low confidence is a handoff, not a shrug.",
    evidenceBoundary: "Implemented source; custom ownership lock and separate outbox rail, without a fresh integrated runtime claim.",
    evidenceKeys: ["parkly.manual-review", "parkly.ownership-lock", "parkly.outbox-rail", "parkly.operational-rails"],
    topology: {
      layers: [
        { id: "parkly-decision", label: "Capture and decision", meaning: "Confidence and next-owner choice" },
        { id: "parkly-review", label: "Human review", meaning: "Manual decision and audit" },
        { id: "parkly-delivery", label: "Separate delivery rail", meaning: "Outbox without inferred review link" },
      ],
      nodes: [
        { id: "parkly-capture", label: "Capture", responsibility: "Supply the operational capture.", layerId: "parkly-decision", sceneSlot: "left-far" },
        { id: "parkly-decision", label: "Decision", responsibility: "Evaluate confidence and choose the next owner.", layerId: "parkly-decision", sceneSlot: "center-mid" },
        { id: "parkly-manual-review", label: "Session or Manual Review", responsibility: "Give a person control of the low-confidence decision.", layerId: "parkly-review", sceneSlot: "right-near" },
        { id: "parkly-audit", label: "Audit", responsibility: "Record the reviewed operational outcome.", layerId: "parkly-review", sceneSlot: "center-near" },
        { id: "parkly-outbox", label: "Outbox", responsibility: "Represent the separate delivery rail without an inferred review link.", layerId: "parkly-delivery", sceneSlot: "separate-bottom" },
      ],
      routes: [
        { id: "parkly-capture-to-decision", from: "parkly-capture", to: "parkly-decision", verb: "supplies", kind: "dependency", evidenceKey: "parkly.manual-review" },
        { id: "parkly-decision-to-review", from: "parkly-decision", to: "parkly-manual-review", verb: "hands off to", kind: "handoff", evidenceKey: "parkly.manual-review" },
        { id: "parkly-review-to-audit", from: "parkly-manual-review", to: "parkly-audit", verb: "records to", kind: "transition", evidenceKey: "parkly.manual-review" },
      ],
      activeHandoff: { routeId: "parkly-decision-to-review", focusNodeId: "parkly-manual-review" },
    },
    narrative: {
      form: "branch-strip",
      title: "Low confidence is a handoff, not a shrug.",
      lead: "Capture reaches a confidence decision. Low confidence transfers ownership to Session or Manual Review before Audit.",
      details: [
        "A custom Redis ownership lock checks ownership around NX/PX and Lua behavior; it is not Redlock.",
        "The Outbox remains a separate delivery rail with no invented Manual Review event.",
      ],
      claimInstanceIds: ["parkly-narrative-review", "parkly-narrative-lock", "parkly-narrative-outbox"],
    },
  },
  {
    id: "tft-local-copilot",
    title: "TFT Local Copilot",
    tier: "supporting",
    order: 5,
    anchor: "#system-tft-local-copilot",
    publicAnchor: "Incomplete runtime boundary",
    summary: "A local RAG experiment assembled far enough to expose its missing seams.",
    evidenceBoundary: "Experimental source components; no registered, migrated, working end-to-end RAG runtime claim.",
    evidenceKeys: ["tft.component-assembly"],
    topology: {
      layers: [
        { id: "tft-source", label: "Source preparation", meaning: "Experimental source input" },
        { id: "tft-retrieval", label: "Retrieval assembly", meaning: "Embedding, storage, and retrieval" },
        { id: "tft-response", label: "Local response", meaning: "Model and stream boundary" },
      ],
      nodes: [
        { id: "tft-source", label: "Source", responsibility: "Supply experimental source material.", layerId: "tft-source", sceneSlot: "left-far" },
        { id: "tft-ingestion", label: "Ingestion", responsibility: "Prepare source material for embedding.", layerId: "tft-source", sceneSlot: "center-far" },
        { id: "tft-embedding", label: "Embedding", responsibility: "Represent the embedding step in source.", layerId: "tft-retrieval", sceneSlot: "left-mid" },
        { id: "tft-vector-store", label: "Vector Store", responsibility: "Represent persisted vector lookup.", layerId: "tft-retrieval", sceneSlot: "center-mid" },
        { id: "tft-retrieval", label: "Retrieval", responsibility: "Assemble candidate context for a local model.", layerId: "tft-retrieval", sceneSlot: "right-mid" },
        { id: "tft-local-model", label: "Local Model", responsibility: "Represent local-model generation without runtime proof.", layerId: "tft-response", sceneSlot: "center-near" },
        { id: "tft-stream", label: "Stream", responsibility: "Represent the streamed response boundary.", layerId: "tft-response", sceneSlot: "right-near" },
      ],
      routes: [
        { id: "tft-source-to-ingestion", from: "tft-source", to: "tft-ingestion", verb: "enters", kind: "transition", evidenceKey: "tft.component-assembly" },
        { id: "tft-ingestion-to-embedding", from: "tft-ingestion", to: "tft-embedding", verb: "prepares", kind: "transition", evidenceKey: "tft.component-assembly" },
        { id: "tft-embedding-to-store", from: "tft-embedding", to: "tft-vector-store", verb: "writes to", kind: "transition", evidenceKey: "tft.component-assembly" },
        { id: "tft-store-to-retrieval", from: "tft-vector-store", to: "tft-retrieval", verb: "supports", kind: "dependency", evidenceKey: "tft.component-assembly" },
        { id: "tft-retrieval-to-model", from: "tft-retrieval", to: "tft-local-model", verb: "supplies context to", kind: "handoff", evidenceKey: "tft.component-assembly" },
        { id: "tft-model-to-stream", from: "tft-local-model", to: "tft-stream", verb: "emits through", kind: "transition", evidenceKey: "tft.component-assembly" },
      ],
      activeHandoff: { routeId: "tft-retrieval-to-model", focusNodeId: "tft-local-model" },
    },
    narrative: {
      form: "lab-note",
      title: "A local RAG experiment assembled far enough to expose its missing seams.",
      lead: "Source, ingestion, embedding, vector storage, retrieval, a local model, and streaming exist as an experimental assembly.",
      details: ["Route-registration and migration gaps keep the complete runtime boundary documented, not implemented."],
      claimInstanceIds: ["tft-narrative-assembly"],
    },
  },
]

export const portfolio = {
  identity: {
    name: "Le Huy",
    role: "Software Engineer",
    target: "Full-time Junior Software Engineer",
    positioning: "Roughly 60% full-stack product-engineering breadth and 40% backend-depth emphasis.",
    strongestDimension: "Backend depth is the strongest technical dimension.",
  },
  opening: {
    proposition: "I build full-stack products from the backend outward: contracts, queues, allocations, review handoffs, and the gates that decide when they ship.",
    atlasLead: "Five systems. Five different failure surfaces.",
    systemsLead: "Each artifact gets its own reading shape.",
    primaryAction: "Work with me",
  },
  contact: {
    email: "huyle210525@gmail.com",
    github: "https://github.com/lhcaps",
    cv: "/le-huy-software-engineer-cv.pdf",
  },
  publication: {
    title: "Le Huy — Software Engineer | Systems Atlas",
    description: "Le Huy's backend-heavy full-stack engineering portfolio: five systems, their handoffs, failure boundaries, and verification evidence.",
    canonicalUrl: "https://lhcaps.github.io/",
    repository: "lhcaps/lhcaps.github.io",
    ref: "refs/heads/main",
  },
  claims,
  claimInstances: [
    { claimInstanceId: "atlas-form-contract", evidenceKey: "form.contract-governance" },
    { claimInstanceId: "atlas-vision-queue", evidenceKey: "vision.queue-handoff" },
    { claimInstanceId: "atlas-booking-revision", evidenceKey: "booking.revision-history" },
    { claimInstanceId: "atlas-parkly-review", evidenceKey: "parkly.manual-review" },
    { claimInstanceId: "atlas-tft-assembly", evidenceKey: "tft.component-assembly" },
    { claimInstanceId: "form-narrative-contract", evidenceKey: "form.contract-governance" },
    { claimInstanceId: "form-narrative-boundaries", evidenceKey: "form.preview-persistence-audit" },
    { claimInstanceId: "form-narrative-gate", evidenceKey: "form.corpus-gate" },
    { claimInstanceId: "vision-narrative-ingestion", evidenceKey: "vision.ingestion-dataset" },
    { claimInstanceId: "vision-narrative-queue", evidenceKey: "vision.queue-handoff" },
    { claimInstanceId: "vision-narrative-evaluation", evidenceKey: "vision.inference-evaluation" },
    { claimInstanceId: "booking-narrative-revision", evidenceKey: "booking.revision-history" },
    { claimInstanceId: "booking-narrative-snapshot", evidenceKey: "booking.hold-snapshot-release" },
    { claimInstanceId: "parkly-narrative-review", evidenceKey: "parkly.manual-review" },
    { claimInstanceId: "parkly-narrative-lock", evidenceKey: "parkly.ownership-lock" },
    { claimInstanceId: "parkly-narrative-outbox", evidenceKey: "parkly.outbox-rail" },
    { claimInstanceId: "tft-narrative-assembly", evidenceKey: "tft.component-assembly" },
    { claimInstanceId: "adaptation-booking-revision", evidenceKey: "booking.revision-history" },
  ],
  systems,
  aiLifecycle: [
    "Intent",
    "Research",
    "Product Brief",
    "PRD",
    "UX Contracts",
    "Spec",
    "Architecture",
    "Story",
    "Scoped Implementation",
    "Harness",
    "Review",
    "Browser QA",
    "Release Evidence",
  ],
  harness: [
    { id: "content-contract", category: "Content contract", acceptanceJob: "Validate five Systems, topology, Claims, and exclusions.", explanation: "Reject missing references, unsafe facts, and private output.", limitation: "Public categories summarize acceptance work; they are not the current release record." },
    { id: "static-gates", category: "Static engineering gates", acceptanceJob: "Typecheck, lint, unit tests, build, audit, and canonical verification.", explanation: "A nonzero child keeps the release unaccepted.", limitation: "Commands, counts, and current results remain internal." },
    { id: "reader-paths", category: "Reader paths", acceptanceJob: "Traverse navigation, five selections, five narratives, and contact.", explanation: "Behavior is tested through semantic reader journeys.", limitation: "This row does not report a current browser run." },
    { id: "accessibility-responsive", category: "Accessibility and responsive", acceptanceJob: "Combine axe with keyboard, focus, contrast, matrix, and overflow review.", explanation: "Screenshots complement behavior and computed layout assertions.", limitation: "Manual and automated evidence remains internal." },
    { id: "scene-states", category: "Scene states", acceptanceJob: "Exercise lazy, ready, bypass, failure, offscreen, and DPR policies.", explanation: "The DOM remains complete in every state.", limitation: "The public page does not claim current GPU or runtime verification." },
    { id: "destinations-identity", category: "Destinations and identity", acceptanceJob: "Validate anchors, contact, CV, metadata, assets, and safe links.", explanation: "Every published destination must resolve at its contracted scope.", limitation: "Machine identity remains a separate endpoint." },
    { id: "review-gates", category: "Review gates", acceptanceJob: "Require product, evidence, visual, motion, accessibility, simplicity, code, and screenshot lenses.", explanation: "Material findings block acceptance.", limitation: "Tracked reports and attestations are not public content." },
    { id: "deployment-attestation", category: "Deployment attestation", acceptanceJob: "Bind one artifact, workflow, deployed identity, production smoke, and remote branch.", explanation: "Exact-SHA hosted acceptance closes the release.", limitation: "The public Harness never publishes current completion." },
    { id: "historical-failed-gate", category: "Historical Failed Gate", acceptanceJob: "Keep stale or nonzero evidence visibly failed.", explanation: "A stale summary kept the gate red. Good.", assertion: "BLOCKED", limitation: "Historical local observation only; it is not the current portfolio release result." },
  ],
  evidenceBoundary: {
    claimClassifications: ["VERIFIED_IMPLEMENTED", "VERIFIED_LOCAL", "VERIFIED_TESTED", "DOCUMENTED_ONLY", "PLANNED", "UNVERIFIED", "PRIVATE_DO_NOT_PUBLISH"],
    releaseAssertions: ["VERIFIED", "OBSERVED", "INFERRED", "BLOCKED"],
    excludedCategories: ["client identity", "price", "screenshot", "credential", "provider configuration", "payment detail", "sensitive deployment information", "physical-room identity", "private Evidence Ledger", "secret", "token"],
  },
  capabilities: [
    { id: "governed-contracts", title: "Governed domain contracts", outcome: "Turn document and policy boundaries into explicit allowed outcomes.", systemIds: ["form-management", "production-booking-operations"] },
    { id: "async-boundaries", title: "Asynchronous boundaries", outcome: "Move long-running work across a named queue handoff without hiding ownership.", systemIds: ["visionflow-studio"] },
    { id: "deterministic-data", title: "Deterministic data flows", outcome: "Bind dataset, evaluation, snapshot, and release identities to reproducible inputs.", systemIds: ["visionflow-studio", "production-booking-operations"] },
    { id: "operational-handoffs", title: "Operational handoffs", outcome: "Make low-confidence or review-required states change owner visibly.", systemIds: ["parkly", "form-management"] },
    { id: "requirement-adaptation", title: "Requirement adaptation", outcome: "Route changing policy through implementation, verification, release, and the next revision.", systemIds: ["production-booking-operations"] },
    { id: "release-verification", title: "Release verification", outcome: "Let deterministic gates and exact-SHA evidence decide when authored work is accepted.", systemIds: ["form-management", "production-booking-operations"] },
  ],
} satisfies PortfolioGraph

export type Portfolio = typeof portfolio
